<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Azure.Identity" Version="1.11.4" />
    <PackageVersion Include="DocX" Version="5.0.0" />
    <PackageVersion Include="FluentAssertions" Version="8.10.0" />
    <PackageVersion Include="MaterialDesignThemes" Version="5.3.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Identity.Client" Version="4.61.3" />
    <PackageVersion Include="Microsoft.Identity.Client.Extensions.Msal" Version="4.61.3" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="Microsoft.SqlServer.TransactSql.ScriptDom" Version="180.18.1" />
    <PackageVersion Include="Microsoft.SqlServer.XEvent.XELite" Version="2024.2.5.1" />
    <PackageVersion Include="Nodify" Version="6.0.0" />
    <PackageVersion Include="QuestPDF" Version="2026.6.0" />
    <PackageVersion Include="System.Formats.Asn1" Version="8.0.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>
