namespace SqlXmlAnalyzer.Core.Privacy;

// Field names/types derived from Microsoft SQL Server 2022 ShowPlan schema 1.571.
// Source: https://schemas.microsoft.com/sqlserver/2004/07/showplan/sql2022/showplanxml.xsd
// This is a conservative field classifier, not a full schema validator.
internal static class ShowPlanFieldCatalog
{
    internal enum FieldKind { Text, Number, Boolean, Enum }
    internal sealed record Field(FieldKind Kind, HashSet<string>? Values = null);
    internal static readonly HashSet<string> Elements = new(StringComparer.Ordinal)
    {
        "ActionColumn",
        "Activation",
        "AdaptiveJoin",
        "AggFunctions",
        "Aggregate",
        "Apply",
        "Arithmetic",
        "Assert",
        "Assign",
        "AssignmentMap",
        "Batch",
        "BatchHashTableBuild",
        "BatchSequence",
        "Bitmap",
        "Bookmarks",
        "BrickRouting",
        "BuildResidual",
        "CLRFunction",
        "Collapse",
        "Column",
        "ColumnGroup",
        "ColumnReference",
        "ColumnsWithNoStatistics",
        "ColumnsWithStaleStatistics",
        "Compare",
        "ComputeScalar",
        "Concat",
        "Condition",
        "Const",
        "ConstTableGet",
        "ConstantScan",
        "Convert",
        "CreateIndex",
        "CursorPlan",
        "DefinedValue",
        "DefinedValues",
        "Delete",
        "DeletedScan",
        "Dispatcher",
        "DistributionKey",
        "Else",
        "EndRange",
        "ExchangeSpillDetails",
        "ExtExtractScan",
        "Extension",
        "ExternalDistributedComputation",
        "ExternalSelect",
        "Filter",
        "ForeignKeyReferenceCheck",
        "ForeignKeyReferencesCheck",
        "FragmentIdColumn",
        "GbAgg",
        "GbApply",
        "GeneratedData",
        "Generic",
        "Get",
        "GroupBy",
        "GroupingSet",
        "GroupingSets",
        "GuessedSelectivity",
        "Hash",
        "HashKeys",
        "HashKeysBuild",
        "HashKeysProbe",
        "HashSpillDetails",
        "IF",
        "Identifier",
        "IndexScan",
        "IndexedViewInfo",
        "InnerSideJoinColumns",
        "Insert",
        "InsertedScan",
        "InternalInfo",
        "Intrinsic",
        "IsNotNull",
        "Join",
        "LocalCube",
        "LogRowScan",
        "Logical",
        "MemoryFractions",
        "MemoryGrantInfo",
        "MemoryGrantWarning",
        "Merge",
        "MergeInterval",
        "MissingIndex",
        "MissingIndexGroup",
        "MissingIndexes",
        "Move",
        "MultipleAssign",
        "NestedLoops",
        "Object",
        "OffsetExpression",
        "OnlineIndex",
        "Operation",
        "OptimizationReplay",
        "OptimizerHardwareDependentProperties",
        "OptimizerStatsUsage",
        "OrderBy",
        "OrderByColumn",
        "OriginalActionColumn",
        "OuterReferences",
        "OuterSideJoinColumns",
        "OutputColumns",
        "OutputList",
        "Parallelism",
        "ParameterList",
        "ParameterSensitivePredicate",
        "ParameterTableScan",
        "Parameterization",
        "PartitionColumns",
        "PartitionId",
        "PartitionRange",
        "PartitionsAccessed",
        "PassThru",
        "PlanAffectingConvert",
        "Predicate",
        "Prefix",
        "PrintDataflow",
        "Probe",
        "ProbeColumn",
        "ProbeResidual",
        "Project",
        "Put",
        "QueryPlan",
        "QueryTimeStats",
        "RangeColumns",
        "RangeExpressions",
        "ReceivePlan",
        "RelOp",
        "RemoteFetch",
        "RemoteModify",
        "RemoteQuery",
        "RemoteRange",
        "RemoteScan",
        "Residual",
        "ResourceEstimate",
        "RollupInfo",
        "RollupLevel",
        "Row",
        "RowCountSpool",
        "RunTimeCountersPerThread",
        "RunTimeInformation",
        "RunTimePartitionSummary",
        "ScalarExpressionList",
        "ScalarInsert",
        "ScalarOperator",
        "SeekKeys",
        "SeekPredicate",
        "SeekPredicateNew",
        "SeekPredicatePart",
        "SeekPredicates",
        "Segment",
        "SegmentColumn",
        "Sequence",
        "SequenceProject",
        "SetPredicate",
        "ShowPlanXML",
        "SimpleUpdate",
        "Sort",
        "SortSpillDetails",
        "SourceColumn",
        "SourceTable",
        "Spatial",
        "SpillOccurred",
        "SpillToTempDb",
        "Split",
        "Spool",
        "StarJoinInfo",
        "StartRange",
        "StatementSetOptions",
        "Statements",
        "StatisticsInfo",
        "StmtCond",
        "StmtCursor",
        "StmtReceive",
        "StmtSimple",
        "StmtUseDb",
        "StoredProc",
        "StreamAggregate",
        "Style",
        "Subquery",
        "Switch",
        "TableScan",
        "TableValuedFunction",
        "TargetColumn",
        "TargetTable",
        "Then",
        "ThreadReservation",
        "ThreadStat",
        "TieColumns",
        "Top",
        "TopExpression",
        "TopSort",
        "TraceFlag",
        "TraceFlags",
        "UDAggObject",
        "UDF",
        "UDTMethod",
        "Union",
        "UnionAll",
        "UnmatchedIndexes",
        "Update",
        "UsedUDXColumns",
        "UserDefinedAggregate",
        "UserDefinedFunction",
        "ValueVector",
        "Values",
        "Wait",
        "WaitStats",
        "Warnings",
        "WindowAggregate",
        "WindowSpool",
        "XcsScan",
    };
    internal static readonly IReadOnlyDictionary<string, Field> Attributes = new Dictionary<string, Field>(StringComparer.Ordinal)
    {
        ["ANSI_NULLS"] = new(FieldKind.Boolean),
        ["ANSI_PADDING"] = new(FieldKind.Boolean),
        ["ANSI_WARNINGS"] = new(FieldKind.Boolean),
        ["ARITHABORT"] = new(FieldKind.Boolean),
        ["ActualCPUms"] = new(FieldKind.Number),
        ["ActualElapsedms"] = new(FieldKind.Number),
        ["ActualEndOfScans"] = new(FieldKind.Number),
        ["ActualExecutionMode"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "Batch", "Row" }),
        ["ActualExecutions"] = new(FieldKind.Number),
        ["ActualJoinType"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "Adaptive Join", "Apply", "Assert", "Batch Hash Table Build", "Bitmap", "Broadcast", "Clustered Index Delete", "Clustered Index Insert", "Clustered Index Merge", "Clustered Index Scan", "Clustered Index Seek", "Clustered Index Update", "Clustered Update", "Collapse", "Columnstore Index Delete", "Columnstore Index Insert", "Columnstore Index Merge", "Columnstore Index Scan", "Columnstore Index Update", "Compute Scalar", "Compute To Control Node", "Concatenation", "Constant Scan", "Constant Table Get", "Control To Compute Nodes", "Delete", "Deleted Scan", "Extensible Column Store Scan", "External Broadcast", "External Extraction Scan", "External Local Streaming", "External Round Robin", "External Select", "External Shuffle", "Filter", "Foreign Key References Check", "GbAgg", "GbApply", "Generic", "Get", "Hash Match", "Index Delete", "Index Insert", "Index Scan", "Index Seek", "Index Spool", "Index Update", "Insert", "Inserted Scan", "Join", "Key Lookup", "LocalCube", "Log Row Scan", "Merge Interval", "Merge Join", "Nested Loops", "Online Index Insert", "Parallelism", "Parameter Table Scan", "Print", "Project", "Put", "RID Lookup", "Rank", "Remote Delete", "Remote Index Scan", "Remote Index Seek", "Remote Insert", "Remote Query", "Remote Scan", "Remote Update", "Row Count Spool", "Segment", "Sequence", "Sequence Project", "Shuffle", "Single Source Round Robin Move", "Sort", "Split", "Stream Aggregate", "Switch", "Table Delete", "Table Insert", "Table Merge", "Table Scan", "Table Spool", "Table Update", "Table-valued function", "Top", "Trim", "UDX", "Union", "Union All", "Window Aggregate", "Window Spool" }),
        ["ActualLobLogicalReads"] = new(FieldKind.Number),
        ["ActualLobPageServerReadAheads"] = new(FieldKind.Number),
        ["ActualLobPageServerReads"] = new(FieldKind.Number),
        ["ActualLobPhysicalReads"] = new(FieldKind.Number),
        ["ActualLobReadAheads"] = new(FieldKind.Number),
        ["ActualLocallyAggregatedRows"] = new(FieldKind.Number),
        ["ActualLogicalReads"] = new(FieldKind.Number),
        ["ActualPageServerPushedPageIDs"] = new(FieldKind.Number),
        ["ActualPageServerPushedReads"] = new(FieldKind.Number),
        ["ActualPageServerReadAheads"] = new(FieldKind.Number),
        ["ActualPageServerReads"] = new(FieldKind.Number),
        ["ActualPageServerRowsRead"] = new(FieldKind.Number),
        ["ActualPageServerRowsReturned"] = new(FieldKind.Number),
        ["ActualPhysicalReads"] = new(FieldKind.Number),
        ["ActualReadAheads"] = new(FieldKind.Number),
        ["ActualRebinds"] = new(FieldKind.Number),
        ["ActualRewinds"] = new(FieldKind.Number),
        ["ActualRows"] = new(FieldKind.Number),
        ["ActualRowsRead"] = new(FieldKind.Number),
        ["ActualScans"] = new(FieldKind.Number),
        ["AdaptiveThresholdRows"] = new(FieldKind.Number),
        ["AggType"] = new(FieldKind.Text),
        ["Alias"] = new(FieldKind.Text),
        ["Ascending"] = new(FieldKind.Boolean),
        ["Assembly"] = new(FieldKind.Text),
        ["AvgRowSize"] = new(FieldKind.Number),
        ["BatchModeOnRowStoreUsed"] = new(FieldKind.Boolean),
        ["BatchSqlHandle"] = new(FieldKind.Text),
        ["Batches"] = new(FieldKind.Number),
        ["BitmapCreator"] = new(FieldKind.Boolean),
        ["Branches"] = new(FieldKind.Number),
        ["BrickId"] = new(FieldKind.Number),
        ["Build"] = new(FieldKind.Text),
        ["CONCAT_NULL_YIELDS_NULL"] = new(FieldKind.Boolean),
        ["CachedPlanSize"] = new(FieldKind.Number),
        ["CardinalityEstimationModelVersion"] = new(FieldKind.Text),
        ["Class"] = new(FieldKind.Text),
        ["CloneAccessScope"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "Both", "Either", "ExactMatch", "Local", "Primary", "Secondary" }),
        ["CloseTime"] = new(FieldKind.Number),
        ["ClusteredMode"] = new(FieldKind.Boolean),
        ["Column"] = new(FieldKind.Text),
        ["ColumnId"] = new(FieldKind.Number),
        ["CompareOp"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "BINARY IS", "BOTH NULL", "EQ", "GE", "GT", "IS", "IS NOT", "IS NOT NULL", "IS NULL", "LE", "LT", "NE", "ONE NULL" }),
        ["CompileCPU"] = new(FieldKind.Number),
        ["CompileMemory"] = new(FieldKind.Number),
        ["CompileTime"] = new(FieldKind.Number),
        ["ComputeSequence"] = new(FieldKind.Boolean),
        ["ComputedColumn"] = new(FieldKind.Boolean),
        ["ConstValue"] = new(FieldKind.Text),
        ["ContainsInlineScalarTsqlUdfs"] = new(FieldKind.Boolean),
        ["ContainsInterleavedExecutionCandidates"] = new(FieldKind.Boolean),
        ["ContainsLedgerTables"] = new(FieldKind.Boolean),
        ["ConvertIssue"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "Cardinality Estimate", "Seek Plan" }),
        ["CpuTime"] = new(FieldKind.Number),
        ["CursorActualType"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "Dynamic", "FastForward", "Keyset", "SnapShot" }),
        ["CursorConcurrency"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "Optimistic", "Pessimistic", "Read Only" }),
        ["CursorName"] = new(FieldKind.Text),
        ["CursorRequestedType"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "Dynamic", "FastForward", "Keyset", "SnapShot" }),
        ["DMLRequestSort"] = new(FieldKind.Boolean),
        ["DOPFeedbackAdjusted"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "No Feedback", "Yes: Adjusting", "Yes: Stable" }),
        ["DataType"] = new(FieldKind.Text),
        ["Database"] = new(FieldKind.Text),
        ["DatabaseContextSettingsId"] = new(FieldKind.Number),
        ["DegreeOfParallelism"] = new(FieldKind.Number),
        ["DesiredMemory"] = new(FieldKind.Number),
        ["Detail"] = new(FieldKind.Boolean),
        ["DiskWrittenInBytes"] = new(FieldKind.Number),
        ["DispatcherPlanHandle"] = new(FieldKind.Text),
        ["Distinct"] = new(FieldKind.Boolean),
        ["DistributionType"] = new(FieldKind.Text),
        ["Dop"] = new(FieldKind.Number),
        ["DynamicSeek"] = new(FieldKind.Boolean),
        ["EdcShowplanXml"] = new(FieldKind.Text),
        ["EffectiveDegreeOfParallelism"] = new(FieldKind.Number),
        ["ElapsedTime"] = new(FieldKind.Number),
        ["End"] = new(FieldKind.Number),
        ["EstimateCPU"] = new(FieldKind.Number),
        ["EstimateIO"] = new(FieldKind.Number),
        ["EstimateRebinds"] = new(FieldKind.Number),
        ["EstimateRewinds"] = new(FieldKind.Number),
        ["EstimateRows"] = new(FieldKind.Number),
        ["EstimateRowsWithoutRowGoal"] = new(FieldKind.Number),
        ["EstimatedAvailableDegreeOfParallelism"] = new(FieldKind.Number),
        ["EstimatedAvailableMemoryGrant"] = new(FieldKind.Number),
        ["EstimatedExecutionMode"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "Batch", "Row" }),
        ["EstimatedJoinType"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "Adaptive Join", "Apply", "Assert", "Batch Hash Table Build", "Bitmap", "Broadcast", "Clustered Index Delete", "Clustered Index Insert", "Clustered Index Merge", "Clustered Index Scan", "Clustered Index Seek", "Clustered Index Update", "Clustered Update", "Collapse", "Columnstore Index Delete", "Columnstore Index Insert", "Columnstore Index Merge", "Columnstore Index Scan", "Columnstore Index Update", "Compute Scalar", "Compute To Control Node", "Concatenation", "Constant Scan", "Constant Table Get", "Control To Compute Nodes", "Delete", "Deleted Scan", "Extensible Column Store Scan", "External Broadcast", "External Extraction Scan", "External Local Streaming", "External Round Robin", "External Select", "External Shuffle", "Filter", "Foreign Key References Check", "GbAgg", "GbApply", "Generic", "Get", "Hash Match", "Index Delete", "Index Insert", "Index Scan", "Index Seek", "Index Spool", "Index Update", "Insert", "Inserted Scan", "Join", "Key Lookup", "LocalCube", "Log Row Scan", "Merge Interval", "Merge Join", "Nested Loops", "Online Index Insert", "Parallelism", "Parameter Table Scan", "Print", "Project", "Put", "RID Lookup", "Rank", "Remote Delete", "Remote Index Scan", "Remote Index Seek", "Remote Insert", "Remote Query", "Remote Scan", "Remote Update", "Row Count Spool", "Segment", "Sequence", "Sequence Project", "Shuffle", "Single Source Round Robin Move", "Sort", "Split", "Stream Aggregate", "Switch", "Table Delete", "Table Insert", "Table Merge", "Table Scan", "Table Spool", "Table Update", "Table-valued function", "Top", "Trim", "UDX", "Union", "Union All", "Window Aggregate", "Window Spool" }),
        ["EstimatedPagesCached"] = new(FieldKind.Number),
        ["EstimatedRowsRead"] = new(FieldKind.Number),
        ["EstimatedTotalSubtreeCost"] = new(FieldKind.Number),
        ["ExclusiveProfileTimeActive"] = new(FieldKind.Boolean),
        ["Expression"] = new(FieldKind.Text),
        ["Filtered"] = new(FieldKind.Boolean),
        ["FirstActiveTime"] = new(FieldKind.Number),
        ["FirstRowTime"] = new(FieldKind.Number),
        ["ForceScan"] = new(FieldKind.Boolean),
        ["ForceSeek"] = new(FieldKind.Boolean),
        ["ForceSeekColumnCount"] = new(FieldKind.Number),
        ["ForcedIndex"] = new(FieldKind.Boolean),
        ["ForeignKeyReferencesCount"] = new(FieldKind.Number),
        ["ForwardOnly"] = new(FieldKind.Boolean),
        ["FragmentElimination"] = new(FieldKind.Text),
        ["FullUpdateForOnlineIndexBuild"] = new(FieldKind.Boolean),
        ["FunctionName"] = new(FieldKind.Text),
        ["GrantWaitTime"] = new(FieldKind.Number),
        ["GrantWarningKind"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "Excessive Grant", "Grant Increase", "Used More Than Granted" }),
        ["GrantedMemory"] = new(FieldKind.Number),
        ["GrantedMemoryKb"] = new(FieldKind.Number),
        ["GraphSequenceIdentifier"] = new(FieldKind.Number),
        ["GraphWorkTableIdentifier"] = new(FieldKind.Number),
        ["GraphWorkTableType"] = new(FieldKind.Number),
        ["GroupExecuted"] = new(FieldKind.Boolean),
        ["HighBoundary"] = new(FieldKind.Number),
        ["HighestLevel"] = new(FieldKind.Number),
        ["HintType"] = new(FieldKind.Text),
        ["HpcDeviceToHostBytes"] = new(FieldKind.Number),
        ["HpcHostToDeviceBytes"] = new(FieldKind.Number),
        ["HpcKernelElapsedUs"] = new(FieldKind.Number),
        ["HpcRowCount"] = new(FieldKind.Number),
        ["HyperScaleOptimizedQueryProcessing"] = new(FieldKind.Text),
        ["HyperScaleOptimizedQueryProcessingUnusedReason"] = new(FieldKind.Text),
        ["Impact"] = new(FieldKind.Number),
        ["Implicit"] = new(FieldKind.Boolean),
        ["InRow"] = new(FieldKind.Boolean),
        ["Index"] = new(FieldKind.Text),
        ["IndexKind"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "Clustered", "FTSChangeTracking", "FTSMapping", "Heap", "NonClustered", "NonClusteredHash", "PrimaryXML", "SecondarySelectiveXML", "SecondaryXML", "SelectiveXML", "Spatial", "ViewClustered", "ViewNonClustered" }),
        ["Input"] = new(FieldKind.Number),
        ["InputMemoryGrant"] = new(FieldKind.Number),
        ["IsAdaptive"] = new(FieldKind.Boolean),
        ["IsClrFunction"] = new(FieldKind.Boolean),
        ["IsCompileTime"] = new(FieldKind.Boolean),
        ["IsDistributed"] = new(FieldKind.Boolean),
        ["IsExternal"] = new(FieldKind.Boolean),
        ["IsExternallyComputed"] = new(FieldKind.Boolean),
        ["IsFull"] = new(FieldKind.Boolean),
        ["IsGraphDBTransitiveClosure"] = new(FieldKind.Boolean),
        ["IsHashDistributed"] = new(FieldKind.Boolean),
        ["IsInterleavedExecuted"] = new(FieldKind.Boolean),
        ["IsMemoryGrantFeedbackAdjusted"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "No: Accurate Grant", "No: Feedback Disabled", "No: First Execution", "Yes: Adjusting", "Yes: Percentile Adjusting", "Yes: Stable" }),
        ["IsNativelyCompiled"] = new(FieldKind.Boolean),
        ["IsNoOp"] = new(FieldKind.Boolean),
        ["IsPercent"] = new(FieldKind.Boolean),
        ["IsReplicated"] = new(FieldKind.Boolean),
        ["IsRoundRobin"] = new(FieldKind.Boolean),
        ["IsScalar"] = new(FieldKind.Boolean),
        ["JoinType"] = new(FieldKind.Text),
        ["LastActiveTime"] = new(FieldKind.Number),
        ["LastRequestedMemory"] = new(FieldKind.Number),
        ["LastRowTime"] = new(FieldKind.Number),
        ["LastUpdate"] = new(FieldKind.Text),
        ["Length"] = new(FieldKind.Number),
        ["Level"] = new(FieldKind.Number),
        ["LocalParallelism"] = new(FieldKind.Boolean),
        ["LogicalOp"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "Aggregate", "Anti Diff", "Assert", "Async Concat", "Batch Hash Table Build", "Bitmap Create", "Clustered Index Scan", "Clustered Index Seek", "Clustered Update", "Collapse", "Compute Scalar", "Concatenation", "Constant Scan", "Constant Table Get", "Cross Join", "Delete", "Deleted Scan", "Distinct", "Distinct Sort", "Distribute Streams", "Eager Spool", "Extensible Column Store Scan", "External Extraction Scan", "External Select", "Filter", "Flow Distinct", "Foreign Key References Check", "Full Outer Join", "Gather Streams", "GbAgg", "GbApply", "Generic", "Get", "Index Scan", "Index Seek", "Inner Apply", "Inner Join", "Insert", "Inserted Scan", "Intersect", "Intersect All", "Key Lookup", "Lazy Spool", "Left Anti Semi Apply", "Left Anti Semi Join", "Left Diff", "Left Diff All", "Left Outer Apply", "Left Outer Join", "Left Semi Apply", "Left Semi Join", "Local Stats", "LocalCube", "Log Row Scan", "Merge", "Merge Interval", "Merge Stats", "Move", "Parameter Table Scan", "Partial Aggregate", "Print", "Project", "Put", "RID Lookup", "Rank", "Remote Delete", "Remote Index Scan", "Remote Index Seek", "Remote Insert", "Remote Query", "Remote Scan", "Remote Update", "Repartition Streams", "Right Anti Semi Join", "Right Diff", "Right Diff All", "Right Outer Join", "Right Semi Join", "Segment", "Sequence", "Sort", "Split", "Switch", "Table Scan", "Table-valued function", "Top", "TopN Sort", "UDX", "Union", "Union All", "Update", "Window Aggregate", "Window Spool" }),
        ["Lookup"] = new(FieldKind.Boolean),
        ["LowBoundary"] = new(FieldKind.Number),
        ["ManyToMany"] = new(FieldKind.Boolean),
        ["MaterializeOperation"] = new(FieldKind.Text),
        ["MaxCompileMemory"] = new(FieldKind.Number),
        ["MaxQueryMemory"] = new(FieldKind.Number),
        ["MaxUsedMemory"] = new(FieldKind.Number),
        ["MemoryGrant"] = new(FieldKind.Number),
        ["MemoryInBytes"] = new(FieldKind.Number),
        ["Method"] = new(FieldKind.Text),
        ["ModificationCount"] = new(FieldKind.Number),
        ["MoveType"] = new(FieldKind.Text),
        ["NUMERIC_ROUNDABORT"] = new(FieldKind.Boolean),
        ["Name"] = new(FieldKind.Text),
        ["NoExpandHint"] = new(FieldKind.Boolean),
        ["NoJoinPredicate"] = new(FieldKind.Boolean),
        ["NoMatchingIndexCount"] = new(FieldKind.Number),
        ["NodeCount"] = new(FieldKind.Number),
        ["NodeId"] = new(FieldKind.Number),
        ["NonParallelPlanReason"] = new(FieldKind.Text),
        ["NumRows"] = new(FieldKind.Number),
        ["OnlineInbuildIndex"] = new(FieldKind.Number),
        ["OnlineIndexBuildMappingIndex"] = new(FieldKind.Number),
        ["OpenTime"] = new(FieldKind.Number),
        ["Operation"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "ADD", "AND", "BIT_ADD", "BIT_AND", "BIT_COMBINE", "BIT_NOT", "BIT_OR", "BIT_XOR", "CONCAT", "DIV", "EQ ALL", "EQ ANY", "EXISTS", "GE ALL", "GE ANY", "GT ALL", "GT ANY", "HASH", "IMPLIES", "IN", "IS", "IS NOT NULL", "IS NULL", "IsFalseOrNull", "LE ALL", "LE ANY", "LT ALL", "LT ANY", "MINUS", "MOD", "MULT", "NE ALL", "NE ANY", "NOT", "OR", "SUB", "XOR" }),
        ["OperationType"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "Fetch", "FetchQuery", "Index Filter", "Index Intersection", "Index Lookup", "PopulateQuery", "ReceivePlanSelect", "ReceivePlanUpdate", "RefreshQuery" }),
        ["Optimized"] = new(FieldKind.Boolean),
        ["Ordered"] = new(FieldKind.Boolean),
        ["Output"] = new(FieldKind.Number),
        ["OutputMemoryGrant"] = new(FieldKind.Number),
        ["PDWAccumulativeCost"] = new(FieldKind.Number),
        ["Parallel"] = new(FieldKind.Boolean),
        ["ParameterCompiledValue"] = new(FieldKind.Text),
        ["ParameterDataType"] = new(FieldKind.Text),
        ["ParameterRuntimeValue"] = new(FieldKind.Text),
        ["ParameterizedPlanHandle"] = new(FieldKind.Text),
        ["ParameterizedText"] = new(FieldKind.Text),
        ["ParentObjectId"] = new(FieldKind.Number),
        ["PartialMatchingIndexCount"] = new(FieldKind.Number),
        ["PartitionCount"] = new(FieldKind.Number),
        ["Partitioned"] = new(FieldKind.Boolean),
        ["PartitioningType"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "Broadcast", "CloneLocation", "Demand", "Hash", "NoPartitioning", "Range", "RoundRobin" }),
        ["PhysicalOp"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "Adaptive Join", "Apply", "Assert", "Batch Hash Table Build", "Bitmap", "Broadcast", "Clustered Index Delete", "Clustered Index Insert", "Clustered Index Merge", "Clustered Index Scan", "Clustered Index Seek", "Clustered Index Update", "Clustered Update", "Collapse", "Columnstore Index Delete", "Columnstore Index Insert", "Columnstore Index Merge", "Columnstore Index Scan", "Columnstore Index Update", "Compute Scalar", "Compute To Control Node", "Concatenation", "Constant Scan", "Constant Table Get", "Control To Compute Nodes", "Delete", "Deleted Scan", "Extensible Column Store Scan", "External Broadcast", "External Extraction Scan", "External Local Streaming", "External Round Robin", "External Select", "External Shuffle", "Filter", "Foreign Key References Check", "GbAgg", "GbApply", "Generic", "Get", "Hash Match", "Index Delete", "Index Insert", "Index Scan", "Index Seek", "Index Spool", "Index Update", "Insert", "Inserted Scan", "Join", "Key Lookup", "LocalCube", "Log Row Scan", "Merge Interval", "Merge Join", "Nested Loops", "Online Index Insert", "Parallelism", "Parameter Table Scan", "Print", "Project", "Put", "RID Lookup", "Rank", "Remote Delete", "Remote Index Scan", "Remote Index Seek", "Remote Insert", "Remote Query", "Remote Scan", "Remote Update", "Row Count Spool", "Segment", "Sequence", "Sequence Project", "Shuffle", "Single Source Round Robin Move", "Sort", "Split", "Stream Aggregate", "Switch", "Table Delete", "Table Insert", "Table Merge", "Table Scan", "Table Spool", "Table Update", "Table-valued function", "Top", "Trim", "UDX", "Union", "Union All", "Window Aggregate", "Window Spool" }),
        ["PlanGuideDB"] = new(FieldKind.Text),
        ["PlanGuideName"] = new(FieldKind.Text),
        ["Precision"] = new(FieldKind.Number),
        ["PrimaryNodeId"] = new(FieldKind.Number),
        ["ProcName"] = new(FieldKind.Text),
        ["QUOTED_IDENTIFIER"] = new(FieldKind.Boolean),
        ["QueryCompilationReplay"] = new(FieldKind.Number),
        ["QueryHash"] = new(FieldKind.Text),
        ["QueryPlanHash"] = new(FieldKind.Text),
        ["QueryStoreStatementHintId"] = new(FieldKind.Number),
        ["QueryStoreStatementHintSource"] = new(FieldKind.Text),
        ["QueryStoreStatementHintText"] = new(FieldKind.Text),
        ["QueryVariantID"] = new(FieldKind.Number),
        ["ReadsFromTempDb"] = new(FieldKind.Number),
        ["RemoteDataAccess"] = new(FieldKind.Boolean),
        ["RemoteDestination"] = new(FieldKind.Text),
        ["RemoteObject"] = new(FieldKind.Text),
        ["RemoteQuery"] = new(FieldKind.Text),
        ["RemoteSource"] = new(FieldKind.Text),
        ["Remoting"] = new(FieldKind.Boolean),
        ["RequestedMemory"] = new(FieldKind.Number),
        ["RequiredMemory"] = new(FieldKind.Number),
        ["ReservedThreads"] = new(FieldKind.Number),
        ["RetrievedFromCache"] = new(FieldKind.Text),
        ["Root"] = new(FieldKind.Boolean),
        ["RowCount"] = new(FieldKind.Boolean),
        ["RowRequalifications"] = new(FieldKind.Number),
        ["Rows"] = new(FieldKind.Number),
        ["SBSFileUrl"] = new(FieldKind.Text),
        ["SamplingPercent"] = new(FieldKind.Number),
        ["Scalable"] = new(FieldKind.Boolean),
        ["ScalarString"] = new(FieldKind.Text),
        ["Scale"] = new(FieldKind.Number),
        ["ScanDirection"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "BACKWARD", "FORWARD" }),
        ["ScanType"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "BINARY IS", "BOTH NULL", "EQ", "GE", "GT", "IS", "IS NOT", "IS NOT NULL", "IS NULL", "LE", "LT", "NE", "ONE NULL" }),
        ["SchedulerId"] = new(FieldKind.Number),
        ["Schema"] = new(FieldKind.Text),
        ["Scope"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "Global", "Session" }),
        ["Script"] = new(FieldKind.Text),
        ["SecurityPolicyApplied"] = new(FieldKind.Boolean),
        ["SegmentReads"] = new(FieldKind.Number),
        ["SegmentSkips"] = new(FieldKind.Number),
        ["SerialDesiredMemory"] = new(FieldKind.Number),
        ["SerialRequiredMemory"] = new(FieldKind.Number),
        ["Server"] = new(FieldKind.Text),
        ["SetPredicateType"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "Insert", "Update" }),
        ["ShuffleColumn"] = new(FieldKind.Text),
        ["ShuffleType"] = new(FieldKind.Text),
        ["SpatialGuess"] = new(FieldKind.Boolean),
        ["SpillLevel"] = new(FieldKind.Number),
        ["SpilledThreadCount"] = new(FieldKind.Number),
        ["Stack"] = new(FieldKind.Boolean),
        ["Start"] = new(FieldKind.Number),
        ["StartupExpression"] = new(FieldKind.Boolean),
        ["StatementCompId"] = new(FieldKind.Number),
        ["StatementEstRows"] = new(FieldKind.Number),
        ["StatementId"] = new(FieldKind.Number),
        ["StatementOptmEarlyAbortReason"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "GoodEnoughPlanFound", "MemoryLimitExceeded", "TimeOut" }),
        ["StatementOptmLevel"] = new(FieldKind.Text),
        ["StatementParameterizationType"] = new(FieldKind.Number),
        ["StatementSqlHandle"] = new(FieldKind.Text),
        ["StatementSubTreeCost"] = new(FieldKind.Number),
        ["StatementText"] = new(FieldKind.Text),
        ["StatementType"] = new(FieldKind.Text),
        ["Statistics"] = new(FieldKind.Text),
        ["StatsCollectionId"] = new(FieldKind.Number),
        ["Storage"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "ColumnStore", "MemoryOptimized", "RowStore" }),
        ["Style"] = new(FieldKind.Number),
        ["Table"] = new(FieldKind.Text),
        ["TableCardinality"] = new(FieldKind.Number),
        ["TableReferenceId"] = new(FieldKind.Number),
        ["TaskAddr"] = new(FieldKind.Number),
        ["TemplatePlanGuideDB"] = new(FieldKind.Text),
        ["TemplatePlanGuideName"] = new(FieldKind.Text),
        ["Thread"] = new(FieldKind.Number),
        ["TopLocation"] = new(FieldKind.Text),
        ["Type"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "CloneLocation", "Region", "Resource", "SingleBrick" }),
        ["UDXName"] = new(FieldKind.Text),
        ["UdfCpuTime"] = new(FieldKind.Number),
        ["UdfElapsedTime"] = new(FieldKind.Number),
        ["UnmatchedIndexes"] = new(FieldKind.Boolean),
        ["Usage"] = new(FieldKind.Enum, new HashSet<string>(StringComparer.Ordinal) { "EQUALITY", "INCLUDE", "INEQUALITY" }),
        ["UsePlan"] = new(FieldKind.Boolean),
        ["UsedMemoryGrant"] = new(FieldKind.Number),
        ["UsedMemoryKb"] = new(FieldKind.Number),
        ["UsedThreads"] = new(FieldKind.Number),
        ["Value"] = new(FieldKind.Text),
        ["Version"] = new(FieldKind.Text),
        ["WaitCount"] = new(FieldKind.Number),
        ["WaitTime"] = new(FieldKind.Number),
        ["WaitTimeMs"] = new(FieldKind.Number),
        ["WaitType"] = new(FieldKind.Text),
        ["WithOrderedPrefetch"] = new(FieldKind.Boolean),
        ["WithTies"] = new(FieldKind.Boolean),
        ["WithUnorderedPrefetch"] = new(FieldKind.Boolean),
        ["WritesToTempDb"] = new(FieldKind.Number),
    };
}
