// =====================================================================================
// HtmlReportGenerator.cs - 生成单文件 HTML 报告
// 内嵌 CSS + Mermaid.js (CDN) + 结构化分析结果
// 支持死锁报告和执行计划报告
// =====================================================================================

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;

namespace SqlXmlAnalyzer
{
    public sealed record HtmlReportSection(
        string Title,
        IReadOnlyList<HtmlReportItem> Items);

    public sealed record HtmlReportItem(
        string Heading,
        string Description,
        string Cause,
        string Recommendation,
        string Severity);

    public static class HtmlReportGenerator
    {
        private const string MermaidCdnUrl = "https://cdn.jsdelivr.net/npm/mermaid@10.9.3/dist/mermaid.min.js";

        /// <summary>
        /// 生成完整的单文件 HTML 报告。所有动态文本均由生成器进行 HTML 编码。
        /// </summary>
        public static string GenerateReport(
            string? originalFilePath,
            string? analysisType,
            string? summaryText,
            string? mermaidCode,
            IReadOnlyList<HtmlReportSection>? sections = null)
        {
            try
            {
                var sb = new StringBuilder();
                string title = analysisType == "Deadlock"
                    ? "SQL Server 死锁分析报告"
                    : "SQL Server 执行计划分析报告";
                string fileToShow = string.IsNullOrEmpty(originalFilePath) ? "未知文件" : originalFilePath;
                string timestamp = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
                string nonce = Guid.NewGuid().ToString("N");
                bool hasMermaid = !string.IsNullOrWhiteSpace(mermaidCode);

                string scriptPolicy = hasMermaid
                    ? $"'nonce-{nonce}' https://cdn.jsdelivr.net"
                    : "'none'";
                string contentSecurityPolicy =
                    $"default-src 'none'; script-src {scriptPolicy}; style-src 'unsafe-inline'; " +
                    "img-src data:; font-src data:; connect-src 'none'; object-src 'none'; " +
                    "base-uri 'none'; form-action 'none'";

                sb.AppendLine("<!DOCTYPE html>");
                sb.AppendLine("<html lang=\"zh-CN\">");
                sb.AppendLine("<head>");
                sb.AppendLine("  <meta charset=\"UTF-8\">");
                sb.AppendLine("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
                sb.AppendLine($"  <meta http-equiv=\"Content-Security-Policy\" content=\"{Encode(contentSecurityPolicy)}\">");
                sb.AppendLine($"  <title>{Encode(title)} - SqlXmlAnalyzer</title>");
                sb.AppendLine("  <style>");
                sb.AppendLine(GetEmbeddedCss());
                sb.AppendLine("  </style>");
                if (hasMermaid)
                {
                    sb.AppendLine("  <!-- Mermaid.js from the only script origin allowed by CSP. -->");
                    sb.AppendLine($"  <script nonce=\"{nonce}\" src=\"{MermaidCdnUrl}\"></script>");
                }
                sb.AppendLine("</head>");
                sb.AppendLine("<body>");
                sb.AppendLine("  <div class=\"container\">");

                sb.AppendLine("    <div class=\"header\">");
                sb.AppendLine($"      <h1>🔍 {Encode(title)}</h1>");
                sb.AppendLine($"      <p class=\"subtitle\">由 SqlXmlAnalyzer v{Encode(Core.ProductInfo.Version)} 生成 | 分析时间: {Encode(timestamp)}</p>");
                sb.AppendLine($"      <p class=\"subtitle\">原始文件: {Encode(fileToShow)}</p>");
                sb.AppendLine("    </div>");

                sb.AppendLine("    <div class=\"section\">");
                sb.AppendLine("      <h2>📋 分析摘要</h2>");
                sb.AppendLine($"      <pre class=\"summary\">{Encode(summaryText ?? "（无摘要信息）")}</pre>");
                sb.AppendLine("    </div>");

                if (hasMermaid)
                {
                    sb.AppendLine("    <div class=\"section\">");
                    sb.AppendLine("      <h2>📊 可视化图表</h2>");
                    sb.AppendLine("      <div class=\"mermaid-container\">");
                    sb.AppendLine($"        <pre class=\"mermaid\">{Encode(mermaidCode)}</pre>");
                    sb.AppendLine("      </div>");
                    sb.AppendLine("      <p class=\"hint\">💡 图表可交互：点击节点、缩放、拖拽</p>");
                    sb.AppendLine("    </div>");
                }

                AppendSections(sb, sections);

                sb.AppendLine("    <div class=\"footer\">");
                sb.AppendLine("      <p>Generated by <strong>SqlXmlAnalyzer</strong> | .NET 8 | 纯 LINQ to XML</p>");
                sb.AppendLine("      <p>提示：本报告为单文件，可离线保存。Mermaid 图表需要网络加载脚本首次渲染。</p>");
                sb.AppendLine("    </div>");
                sb.AppendLine("  </div>");

                if (hasMermaid)
                {
                    sb.AppendLine($"  <script nonce=\"{nonce}\">");
                    sb.AppendLine("    mermaid.initialize({");
                    sb.AppendLine("      startOnLoad: true,");
                    sb.AppendLine("      securityLevel: 'strict',");
                    sb.AppendLine("      theme: 'default',");
                    sb.AppendLine("      flowchart: { useMaxWidth: true, htmlLabels: false }");
                    sb.AppendLine("    });");
                    sb.AppendLine("  </script>");
                }

                sb.AppendLine("</body>");
                sb.AppendLine("</html>");

                return sb.ToString();
            }
            catch (Exception ex)
            {
                Logger.LogException("HtmlReportGenerator.GenerateReport", ex);
                return $"<html><body><h1>分析报告生成失败</h1><p>{Encode(ex.Message)}</p></body></html>";
            }
        }

        private static void AppendSections(
            StringBuilder sb,
            IReadOnlyList<HtmlReportSection>? sections)
        {
            if (sections == null)
            {
                return;
            }

            foreach (var section in sections.Where(section => section != null))
            {
                sb.AppendLine("    <div class=\"section\">");
                sb.AppendLine($"      <h2>{Encode(section.Title)}</h2>");
                sb.AppendLine("      <div class=\"analysis\">");

                foreach (var item in section.Items ?? Array.Empty<HtmlReportItem>())
                {
                    if (item == null)
                    {
                        continue;
                    }

                    string severityClass = GetSeverityClass(item.Severity);
                    sb.AppendLine($"        <article class=\"report-item {severityClass}\">");
                    sb.AppendLine($"          <h3>{Encode(item.Heading)} <span class=\"severity\">{Encode(item.Severity)}</span></h3>");
                    AppendField(sb, "描述", item.Description);
                    AppendField(sb, "可能原因", item.Cause);
                    AppendField(sb, "推荐措施", item.Recommendation);
                    sb.AppendLine("        </article>");
                }

                sb.AppendLine("      </div>");
                sb.AppendLine("    </div>");
            }
        }

        private static void AppendField(StringBuilder sb, string label, string? value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return;
            }

            sb.AppendLine($"          <p><strong>{label}:</strong> {EncodeMultiline(value)}</p>");
        }

        private static string GetSeverityClass(string? severity)
        {
            return severity?.Trim().ToUpperInvariant() switch
            {
                "CRITICAL" or "HIGH" => "severity-high",
                "WARNING" or "MEDIUM" => "severity-medium",
                _ => "severity-low"
            };
        }

        private static string Encode(string? value)
        {
            return WebUtility.HtmlEncode(value ?? string.Empty);
        }

        private static string EncodeMultiline(string? value)
        {
            return Encode(value)
                .Replace("\r\n", "<br/>", StringComparison.Ordinal)
                .Replace("\r", "<br/>", StringComparison.Ordinal)
                .Replace("\n", "<br/>", StringComparison.Ordinal);
        }

        private static string GetEmbeddedCss()
        {
            return @"
:root {
  --primary: #0066cc;
  --danger: #cc0000;
  --warning: #ff9800;
  --bg: #f8f9fa;
  --card: #ffffff;
  --text: #212529;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  background: var(--bg);
  color: var(--text);
  margin: 0;
  padding: 20px;
  line-height: 1.6;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  background: var(--card);
  border-radius: 12px;
  box-shadow: 0 10px 30px rgba(0,0,0,0.08);
  overflow: hidden;
}

.header {
  background: linear-gradient(135deg, #0066cc, #004d99);
  color: white;
  padding: 30px 40px;
  text-align: center;
}

.header h1 {
  margin: 0 0 10px 0;
  font-size: 2.2rem;
}

.subtitle {
  margin: 5px 0;
  opacity: 0.9;
  font-size: 0.95rem;
}

.section {
  padding: 25px 40px;
  border-bottom: 1px solid #eee;
}

.section:last-child {
  border-bottom: none;
}

h2 {
  color: #0066cc;
  border-bottom: 3px solid #e6f0ff;
  padding-bottom: 8px;
  margin-top: 0;
}

.summary {
  background: #f1f3f5;
  padding: 15px;
  border-radius: 8px;
  white-space: pre-wrap;
  font-family: Consolas, Monaco, monospace;
  font-size: 0.92rem;
  border-left: 5px solid #0066cc;
}

.mermaid-container {
  background: #fafafa;
  border: 1px solid #dee2e6;
  border-radius: 8px;
  padding: 15px;
  margin: 15px 0;
  min-height: 200px;
}

.hint {
  font-size: 0.85rem;
  color: #666;
  font-style: italic;
}

.analysis {
  display: grid;
  gap: 12px;
}

.report-item {
  border: 1px solid #dee2e6;
  border-left-width: 5px;
  border-radius: 6px;
  padding: 14px 16px;
  background: #fff;
}

.report-item h3 {
  margin: 0 0 8px;
}

.report-item p {
  margin: 7px 0 0;
}

.severity {
  font-size: 0.78rem;
  font-weight: normal;
  margin-left: 6px;
}

.severity-high {
  border-left-color: var(--danger);
  background: #fff5f5;
}

.severity-medium {
  border-left-color: var(--warning);
  background: #fffaf0;
}

.severity-low {
  border-left-color: var(--primary);
  background: #f5f9ff;
}

.footer {
  text-align: center;
  padding: 20px;
  background: #f8f9fa;
  font-size: 0.85rem;
  color: #666;
}

pre.mermaid {
  margin: 0;
}

@media (max-width: 768px) {
  .container { margin: 10px; border-radius: 8px; }
  .section { padding: 15px 20px; }
}
";
        }

        /// <summary>
        /// 便捷方法：直接保存 HTML 报告到文件。
        /// </summary>
        public static string SaveReport(
            string? originalFilePath,
            string? analysisType,
            string? summaryText,
            string? mermaidCode,
            IReadOnlyList<HtmlReportSection>? sections = null,
            string? outputPath = null)
        {
            Logger.Info($"SaveReport: 开始保存 HTML 报告 | originalFilePath={originalFilePath}, type={analysisType}");

            try
            {
                string html = GenerateReport(originalFilePath, analysisType, summaryText, mermaidCode, sections);

                if (string.IsNullOrEmpty(outputPath))
                {
                    string dir = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "reports");
                    Directory.CreateDirectory(dir);
                    string timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
                    string safeName = string.IsNullOrEmpty(originalFilePath)
                        ? "unknown"
                        : Path.GetFileNameWithoutExtension(originalFilePath);
                    outputPath = Path.Combine(dir, $"{analysisType}_{safeName}_{timestamp}.html");
                }
                else
                {
                    string? dir = Path.GetDirectoryName(outputPath);
                    if (!string.IsNullOrEmpty(dir))
                    {
                        Directory.CreateDirectory(dir);
                    }
                }

                File.WriteAllText(outputPath, html, Encoding.UTF8);
                Logger.Info($"SaveReport: 报告已成功保存到: {outputPath}");
                return outputPath;
            }
            catch (Exception ex)
            {
                Logger.LogException("HtmlReportGenerator.SaveReport", ex);
                try
                {
                    string fallbackPath = Path.Combine(
                        AppDomain.CurrentDomain.BaseDirectory,
                        $"fallback_report_{DateTime.Now:yyyyMMdd_HHmmss}.html");
                    string html = GenerateReport(originalFilePath, analysisType, summaryText, mermaidCode, sections);
                    File.WriteAllText(fallbackPath, html, Encoding.UTF8);
                    Logger.Warning($"SaveReport: 已将报告备份保存到: {fallbackPath}");
                    return fallbackPath;
                }
                catch (Exception fallbackEx)
                {
                    Logger.LogException("HtmlReportGenerator.SaveReport (Fallback)", fallbackEx);
                }

                throw;
            }
        }
    }
}
