// =====================================================================================
// HtmlReportGenerator.cs - 生成自包含的 HTML 单文件报告
// 内嵌 CSS + Mermaid.js (CDN) + 分析结果 + 可交互的 Mermaid 图
// 支持死锁报告和执行计划报告
// =====================================================================================

#nullable disable

using System;
using System.IO;
using System.Text;
using System.Xml.Linq;

namespace SqlXmlAnalyzer
{
    public static class HtmlReportGenerator
    {
        /// <summary>
        /// 生成完整的自包含 HTML 报告
        /// </summary>
        public static string GenerateReport(
            string originalFilePath,
            string analysisType, // "Deadlock" or "ExecutionPlan"
            string summaryText,
            string mermaidCode,
            string additionalAnalysis = "")
        {
            try
            {
                var sb = new StringBuilder();

                string title = (analysisType == "Deadlock") 
                    ? "SQL Server 死锁分析报告" 
                    : "SQL Server 执行计划分析报告";

                string fileToShow = string.IsNullOrEmpty(originalFilePath) ? "未知文件" : originalFilePath;
                string timestamp = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");

                sb.AppendLine("<!DOCTYPE html>");
                sb.AppendLine("<html lang=\"zh-CN\">");
                sb.AppendLine("<head>");
                sb.AppendLine("  <meta charset=\"UTF-8\">");
                sb.AppendLine("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
                sb.AppendLine($"  <title>{title} - SqlXmlAnalyzer</title>");
                sb.AppendLine("  <style>");
                sb.AppendLine(GetEmbeddedCss());
                sb.AppendLine("  </style>");
                sb.AppendLine("  <!-- Mermaid.js from CDN for rendering diagrams -->");
                sb.AppendLine("  <script src=\"https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js\"></script>");
                sb.AppendLine("</head>");
                sb.AppendLine("<body>");
                sb.AppendLine("  <div class=\"container\">");
                
                // Header
                sb.AppendLine("    <div class=\"header\">");
                sb.AppendLine($"      <h1>🔍 {title}</h1>");
                sb.AppendLine($"      <p class=\"subtitle\">由 SqlXmlAnalyzer v1.0.0 生成 | 分析时间: {timestamp}</p>");
                sb.AppendLine($"      <p class=\"subtitle\">原始文件: {fileToShow}</p>");
                sb.AppendLine("    </div>");

                // Summary
                string summarySafe = summaryText ?? "（无摘要信息）";
                sb.AppendLine("    <div class=\"section\">");
                sb.AppendLine("      <h2>📋 分析摘要</h2>");
                sb.AppendLine($"      <pre class=\"summary\">{System.Net.WebUtility.HtmlEncode(summarySafe)}</pre>");
                sb.AppendLine("    </div>");

                // Mermaid Diagram
                if (!string.IsNullOrWhiteSpace(mermaidCode))
                {
                    sb.AppendLine("    <div class=\"section\">");
                    sb.AppendLine("      <h2>📊 可视化图表</h2>");
                    sb.AppendLine("      <div class=\"mermaid-container\">");
                    string encodedMermaid = System.Net.WebUtility.HtmlEncode(mermaidCode);
                    sb.AppendLine($"        <pre class=\"mermaid\">{encodedMermaid}</pre>");
                    sb.AppendLine("      </div>");
                    sb.AppendLine("      <p class=\"hint\">💡 图表可交互：点击节点、缩放、拖拽</p>");
                    sb.AppendLine("    </div>");
                }

                // Additional analysis (patterns, suggestions, etc.)
                if (!string.IsNullOrWhiteSpace(additionalAnalysis))
                {
                    sb.AppendLine("    <div class=\"section\">");
                    sb.AppendLine("      <h2>💡 详细诊断与建议</h2>");
                    sb.AppendLine($"      <div class=\"analysis\">{additionalAnalysis}</div>");
                    sb.AppendLine("    </div>");
                }

                // Footer
                sb.AppendLine("    <div class=\"footer\">");
                sb.AppendLine("      <p>Generated by <strong>SqlXmlAnalyzer</strong> | .NET 8 | 纯 LINQ to XML</p>");
                sb.AppendLine("      <p>提示：本报告为单文件，可离线保存。Mermaid 图表需要网络加载脚本首次渲染。</p>");
                sb.AppendLine("    </div>");

                sb.AppendLine("  </div>");

                // Mermaid initialization script
                sb.AppendLine("  <script>");
                sb.AppendLine("    mermaid.initialize({");
                sb.AppendLine("      startOnLoad: true,");
                sb.AppendLine("      theme: 'default',");
                sb.AppendLine("      flowchart: { useMaxWidth: true, htmlLabels: true }");
                sb.AppendLine("    });");
                sb.AppendLine("    // Re-render on resize for better UX");
                sb.AppendLine("    window.addEventListener('resize', () => {");
                sb.AppendLine("      document.querySelectorAll('.mermaid').forEach(el => {");
                sb.AppendLine("        el.removeAttribute('data-processed');");
                sb.AppendLine("      });");
                sb.AppendLine("      mermaid.init();");
                sb.AppendLine("    });");
                sb.AppendLine("  </script>");

                sb.AppendLine("</body>");
                sb.AppendLine("</html>");

                return sb.ToString();
            }
            catch (Exception ex)
            {
                Logger.LogException("HtmlReportGenerator.GenerateReport", ex);
                return $"<html><body><h1>分析报告生成失败</h1><p>{ex.Message}</p></body></html>";
            }
        }

        private static string GetEmbeddedCss()
        {
            return @"
:root {
  --primary: #0066cc;
  --danger: #cc0000;
  --success: #28a745;
  --warning: #ff9800;
  --bg: #f8f9fa;
  --card: #ffffff;
  --text: #212529;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  background: var(--bg);
  color: var(--text);
  margin: 0;
  padding: 20px;
  line-height: 1.6;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  background: var(--card);
  border-radius: 12px;
  box-shadow: 0 10px 30px rgba(0,0,0,0.08);
  overflow: hidden;
}

.header {
  background: linear-gradient(135deg, #0066cc, #004d99);
  color: white;
  padding: 30px 40px;
  text-align: center;
}

.header h1 {
  margin: 0 0 10px 0;
  font-size: 2.2rem;
}

.subtitle {
  margin: 5px 0;
  opacity: 0.9;
  font-size: 0.95rem;
}

.section {
  padding: 25px 40px;
  border-bottom: 1px solid #eee;
}

.section:last-child {
  border-bottom: none;
}

h2 {
  color: #0066cc;
  border-bottom: 3px solid #e6f0ff;
  padding-bottom: 8px;
  margin-top: 0;
}

.summary {
  background: #f1f3f5;
  padding: 15px;
  border-radius: 8px;
  white-space: pre-wrap;
  font-family: Consolas, Monaco, monospace;
  font-size: 0.92rem;
  border-left: 5px solid #0066cc;
}

.mermaid-container {
  background: #fafafa;
  border: 1px solid #dee2e6;
  border-radius: 8px;
  padding: 15px;
  margin: 15px 0;
  min-height: 200px;
}

.hint {
  font-size: 0.85rem;
  color: #666;
  font-style: italic;
}

.analysis {
  background: #fff;
}

.footer {
  text-align: center;
  padding: 20px;
  background: #f8f9fa;
  font-size: 0.85rem;
  color: #666;
}

pre.mermaid {
  margin: 0;
}

@media (max-width: 768px) {
  .container { margin: 10px; border-radius: 8px; }
  .section { padding: 15px 20px; }
}
";
        }

        /// <summary>
        /// 便捷方法：直接保存 HTML 报告到文件
        /// </summary>
        public static string SaveReport(
            string originalFilePath,
            string analysisType,
            string summaryText,
            string mermaidCode,
            string additionalAnalysis = "",
            string outputPath = null)
        {
            Logger.Info($"SaveReport: 开始保存 HTML 报告 | originalFilePath={originalFilePath}, type={analysisType}");
            
            try
            {
                string html = GenerateReport(originalFilePath, analysisType, summaryText, mermaidCode, additionalAnalysis);

                if (string.IsNullOrEmpty(outputPath))
                {
                    string dir = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "reports");
                    Directory.CreateDirectory(dir);
                    string timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
                    string safeName = string.IsNullOrEmpty(originalFilePath) ? "unknown" : Path.GetFileNameWithoutExtension(originalFilePath);
                    outputPath = Path.Combine(dir, $"{analysisType}_{safeName}_{timestamp}.html");
                }
                else
                {
                    string dir = Path.GetDirectoryName(outputPath);
                    if (!string.IsNullOrEmpty(dir))
                    {
                        Directory.CreateDirectory(dir);
                    }
                }

                File.WriteAllText(outputPath, html, Encoding.UTF8);
                Logger.Info($"SaveReport: 报告已成功保存到: {outputPath}");
                return outputPath;
            }
            catch (Exception ex)
            {
                Logger.LogException("HtmlReportGenerator.SaveReport", ex);
                // 试图在应用程序目录的根部进行备用保存
                try
                {
                    string fallbackPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, $"fallback_report_{DateTime.Now:yyyyMMdd_HHmmss}.html");
                    string html = GenerateReport(originalFilePath, analysisType, summaryText, mermaidCode, additionalAnalysis);
                    File.WriteAllText(fallbackPath, html, Encoding.UTF8);
                    Logger.Warning($"SaveReport: 已将报告备份保存到: {fallbackPath}");
                    return fallbackPath;
                }
                catch (Exception fallbackEx)
                {
                    Logger.LogException("HtmlReportGenerator.SaveReport (Fallback)", fallbackEx);
                }
                throw;
            }
        }
    }
}


